trigger:
- master
- Dev

pr:
- master
- Dev

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'


steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: |
    dotnet tool install --global dotnet-reportgenerator-globaltool
    dotnet tool install --global dotnet-sonarscanner
  displayName: 'Install .NET tools'

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '$(solution)'
  displayName: 'Restore'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(solution)'
    arguments: '--configuration $(buildConfiguration)'
  displayName: 'Build'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '$(Build.SourcesDirectory)/TestAPI/TestAPI.csproj'
    arguments: '--configuration $(buildConfiguration) --logger trx --collect:"XPlat Code Coverage" --diag:log.txt'
  displayName: 'Test'

- script: |
    reportgenerator -reports:$(solution)/TestAPI/TestResesults/**/coverage.cobertura.xml -targetdir:$(Build.ArtifactStagingDirectory)/CoverageReport
  displayName: 'Generate coverage report'

- script: |
    echo "Listing coverage report files..."
    ls -R $(Build.ArtifactStagingDirectory)/CoverageReport
  displayName: 'List Coverage Report Files'

- task: PublishCodeCoverageResults@2
  inputs:
    summaryFileLocation: '$(Agent.TempDirectory)/**/coverage.cobertura.xml'  

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    zipAfterPublish: true
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
  displayName: 'ZIP'


- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)/API.zip'
    artifactName: 'API'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)/Minimal.zip'
    artifactName: 'Minimal'

